name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

env:
  QT_QPA_PLATFORM: offscreen
  CGNS_GUI_FORCE_OFFSCREEN: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  XDG_RUNTIME_DIR: /tmp/runtime-cgns

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libegl1

      - name: Prepare runtime directory
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p "$XDG_RUNTIME_DIR"
          chmod 700 "$XDG_RUNTIME_DIR"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Lint with Ruff
        run: ruff check .

      - name: Run pytest
        run: pytest

      - name: Build distributables
        run: python tools/build_package.py

      - name: Smoke test wheel installation
        shell: bash
        run: |
          set -euo pipefail
          wheel=$(ls dist/*.whl | head -n1)
          python -m pip install --force-reinstall --no-deps "$wheel"
          python -c "import cgns_gui; print('Import OK on', __import__('platform').platform())"
