name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

env:
  QT_QPA_PLATFORM: offscreen
  CGNS_GUI_FORCE_OFFSCREEN: "1"
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  XDG_RUNTIME_DIR: /tmp/runtime-cgns

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.10"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          miniconda-version: "latest"
          activate-environment: cgns-gui-ci
          environment-file: environment-ci.yml

      - name: Install system dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgl1 libegl1

      - name: Prepare runtime directory
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir -p "$XDG_RUNTIME_DIR"
          chmod 700 "$XDG_RUNTIME_DIR"

      - name: Install pyCGNS via conda
        shell: bash -el {0}
        run: |
          conda install -c conda-forge pycgns -y

      - name: Install project dependencies
        shell: bash -el {0}
        run: |
          pip install -e .[dev]

      - name: Lint with Ruff
        shell: bash -el {0}
        run: ruff check .

      - name: Run pytest
        shell: bash -el {0}
        run: pytest

      - name: Build distributables
        shell: bash -el {0}
        run: python tools/build_package.py

      - name: Smoke test wheel installation
        shell: bash -el {0}
        run: |
          set -euo pipefail
          wheel=$(ls dist/*.whl | head -n1)
          pip install --force-reinstall --no-deps "$wheel"
          python -c "import cgns_gui; print('Import OK on', __import__('platform').platform())"
